apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: backend
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: api-server
          image: $IMAGE
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: $DB_HOST
            - name: DB_PORT
              value: $DB_PORT
            - name: DB_NAME
              value: $DB_NAME
            - name: DB_USER
              value: $DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: $SECRET_NAME
                  key: $SECRET_KEY


---

apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
  selector:
    app: backend

### For this exercise you're going to install MariaDB with HELM (from bitnami repo)
