apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  labels:
    app: backend
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: api-server
          image: $IMAGE
          ports:
            - containerPort: $PORT
