name: Java CI

on:
  push:
    branches:
      - main
env:
  RUN_NUMBER: ${{ github.run_number }}
  IMAGE: be

jobs:
  test-mvn-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'corretto'
      - name: Test with Maven
        run: mvn clean test

  login_then_push_dockerhub:
    name: docker image build and push
    needs: test-mvn-project
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:v2.1.${{ github.run_number }}
  deploy-to-cloudshell-minikube:
    name: Deploy to minikube
    needs: login_then_push_dockerhub
    runs-on: [self-hosted, Linux, X64, cloudshell ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Find and Replace IMAGE
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$IMAGE"
          replace: ${{ secrets.DOCKER_HUB_USERNAME }}/${{ env.IMAGE }}:v2.1.${{ github.run_number }}
          regex: false
      - name: Find and Replace REPLICAS
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "$REPLICAS"
          replace: 1
          regex: false

      - name: Deploy on Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: apply -f kube-deploy.yaml
